[project]
name = "blobs"
version = "0.1.0"
description = "Add a short description here"
authors = ["Hessam Mehr <Hessam.Mehr@glasgow.ac.uk>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
segment-anything = "1.0.*"
numpy = "1.26.2.*"
scikit-learn = "1.3.2.*"
opencv = "4.8.1.*"
tqdm = "4.66.1.*"
seaborn = "0.13.0.*"
matplotlib = "3.8.2.*"
pandas = "2.1.3.*"
